id: PD87EB27B
initial_creation_type: input
source_metadata:
  Title: Hetubindu of Dharmakirti
  Editor: Gokhale, P. P.
  Publisher: Sri Satguru Publications
  Place of Publication: India
  Year: '1997'
  Hetubinduḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:48:10.330716'
last_modified_at: '2022-03-08T16:48:10.330723'
